version: "3"
services:
  book_api:
    restart: unless-stopped
    depends_on:
      - book_postgres
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    environment:
      - DATABASE_HOST=book_postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=book_api
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - NODE_ENV=development

  book_postgres:
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book_api
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
